# Copyright 2021 LINBIT HA-Solutions GmbH
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  publish-path:
    type: string
    default: /var/lib/kubelet
    description: |
      The path (on the host) where kubelet expects the volumes to be published.

      For microk8s, use /var/snap/microk8s/common/var/lib/kubelet.
