# Copyright 2021 LINBIT HA-Solutions GmbH
# See LICENSE file for licensing details.
options:
  publish-path:
    type: string
    default: /var/snap/microk8s/common/var/lib/kubelet
    description: |
      The path (on the host) where kubelet expects the volumes to be published.

      For unmodified kubernetes, use /var/lib/kubelet.
