# Copyright 2021 LINBIT HA-Solutions GmbH
# See LICENSE file for licensing details.

options:
  linstor-control-port:
    default: 3366
    description: Port the Linstor Satellite will listen on for control plane commands.
    type: int
  injection-mode:
    type: string
    default: auto
    description: > 
      How to inject the kernel module. Can be "compile", "package" or "auto". The default (auto) compiles
      unless a LINBIT image is used.
  storage-pools:
    type: string
    default: ''
    description: >
      A list of storage pools to configure. Entries are space-separated, every entry is itself a comma-separated list of key-value pairs.
      The possible keys and their meaning are:
      - provider (required): LINSTOR storage pool provider, possible values are: DISKLESS, EXOS, FILE, FILE_THIN, LVM, LVM_THIN, OPENFLEX_TARGET, SPDK, ZFS, ZFS_THIN
      - name (required): The name assigned to the storage pool in LINSTOR.
      - provider_name: Provider specific name of the storage pool. For example, the name of the Volume Group for LVM pools, the zpool for ZFS pools, etc. Required except when creating a diskless pool.
      - devices: Optionally, let LINSTOR create the provider pool on the given device. Multiple devices can be specified.

      Example 1: To configure a LINSTOR LVMTHIN storage pool named "thinpool" based on an existing LVM Thin Pool "storage/thinpool", use:
        provider=LVM_THIN,provider_name=storage/thinpool,name=thinpool

      Example 2: To configure a LINSTOR ZFS storage pool named "ssds" based on unconfigured devices "/dev/sdc" and "/dev/sdd" use:
        provider=ZFS_THIN,provider_name=ssds,name=ssds,devices=/dev/sdc,devices=/dev/sdd
