apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc-clone
spec:
  containers:
  - image: busybox
    name: demo
    command: ["init", "tail", "-f", "/dev/null"]
    volumeMounts:
    - name: data
      mountPath: /mnt/data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: example-pvc-clone
