apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-clone
spec:
  storageClassName: example-storageclass
  accessModes:
  - ReadWriteOnce
  dataSource:
    name: data-sts-with-pvc-0
    kind: PersistentVolumeClaim
    apiGroup: ""
  resources:
    requests:
      storage: 2Gi
