apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-restored
spec:
  storageClassName: example-storageclass
  accessModes:
  - ReadWriteOnce
  dataSource:
    name: data-sts-snapshot-0
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  resources:
    requests:
      storage: 2Gi
