[values]
KubeSprayImage = "quay.io/kubespray/kubespray:v2.16.0"

[[steps]]
[steps.docker]
image = "{{.KubeSprayImage}}"
command = [
    "sh", "-exc",
    """
    ansible-inventory --inventory /virter/workspace/virter/inventory --yaml --list
    ansible-playbook \
      --inventory /virter/workspace/virter/inventory \
      --tags always,facts,preinstall,download,bootstrap-os,container-engine \
      --extra-vars @/virter/workspace/virter/config/provision.yml \
      /virter/workspace/virter/base-image-play.yml
    """,
]
