[values]
KubeSprayImage = "quay.io/kubespray/kubespray:v2.16.0"

[[steps]]
[steps.docker]
image = "{{.KubeSprayImage}}"
command = [
    "sh", "-exc",
    """
    mkdir -p /virter/out

    ansible-inventory --inventory /virter/workspace/virter/inventory --yaml --list
    ansible-playbook \
      --inventory /virter/workspace/virter/inventory \
      --extra-vars artifacts_dir=/virter/out/artifacts \
      --extra-vars credentials_dir=/virter/out/credentials \
      --skip-tags container-engine,bootstrap-os,preinstall,download \
      /virter/workspace/virter/cluster-play.yml
    """,
]
[steps.docker.copy]
source = "/virter/out"
dest = "./virter"
